project:
  type: website
  output-dir: _site

website:
  title: "The Bernoulli Family: A Mathematical Legacy"
  navbar:
    left:
      - href: bernoulli.qmd
        text: Home
      - href: chapters/chapter1.qmd
        text: Jacob
      - href: chapters/chapter2.qmd
        text: Johann
      - href: chapters/chapter3.qmd
        text: Daniel

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 2
    number-sections: true

execute:
  freeze: auto
