project:
  type: website
  output-dir: _site
  render:
    - bernoulli.qmd
website:
  title: "The Bernoulli Family: A Mathematical Legacy"
  navbar:
    left:
      - href: bernoulli.qmd
        text: Home
      - href: bernoulli.qmd#jacob-bernoulli-1655-1705
        text: Jacob
      - href: bernoulli.qmd#johann-bernoulli-1667-1748
        text: Johann
      - href: bernoulli.qmd#nicolaus-i-bernoulli-1687-1759
        text: Nicolaus I
      - href: bernoulli.qmd#daniel-bernoulli-1700-1782
        text: Daniel
      - href: bernoulli.qmd#leonhard-euler-1707-1783
        text: Euler

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 2
    number-sections: true

execute:
  freeze: auto
